The goal of this notebook is convert the chordonomicon data set to make each song a matrix where each column records a single chord. 

Steps:

1. Import the chordonomicon data set, drop all columns except for 'id' and 'chords'
2. Remove section marker info from chords i.e. remove \<intro_1\>
3. For each song, convert each chord into a vector, then concatenate them into a matrix 

In [2]:
# importing basic packages
import numpy as np
import pandas as pd
import matplotlib as plt
import ast

# read in the data set
df = pd.read_csv('../data/chordonomicon.csv', low_memory=False)

In [3]:
# Read the mapping CSV file
chord_relations = pd.read_csv('../data/chords_mapping.csv')

# Create a dictionary with keys the "chords" and values the "degrees"
chord_degrees = dict(zip(chord_relations['Chords'], chord_relations['Degrees']))
for key, value in chord_degrees.items():
    chord_degrees[key] = ast.literal_eval(value)
    
# full list of chords from the chords_mapping csv
known_chords = list(chord_degrees.keys())
assert(len(known_chords) == len(set(known_chords))) # Validating no duplicates

# some examples of what the string labels for known chords look like
print(known_chords[0:10])

['C7', 'Cmaj7', 'C9', 'Cmaj9', 'Cmajs9', 'Cb9', 'Cb79', 'Cb7b9', 'C7b9', 'C7sus2']


In [4]:
# some examples of what chords look like in this data file
print("Number of known chords: ",len(chord_degrees))
print("C major: \t",chord_degrees['C'])
print("C major 7: \t",chord_degrees['Cmaj7'])
print("C minor: \t",chord_degrees['Cmin'])

Number of known chords:  2793
C major: 	 [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
C major 7: 	 [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1]
C minor: 	 [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]


In [5]:
# drop all columns except for chords and genres
chord_data = df[['chords','genres']]
chord_data.sample(5)

chords  \
117136  <intro_1> D7sus2 D7sus4 D7sus2 D7sus4 <verse_1...   
536888  C F C F C F C F C F C F C F Amin F C G C F C F...   
223501  G C G D G C G D G C G D G C G D G C G D G C G ...   
365904  G C Emin D G C Emin D G C Emin D G C Emin D C ...   
642160  Gno3d Bbno3d Cno3d Bbno3d Cno3d C G Amin Emin ...   

                                                   genres  
117136                                                NaN  
536888                                        omaha indie  
223501  alberta country"canadian contemporary country"...  
365904                 alternative country"heartland rock  
642160                                                NaN

In [6]:
# replacing spaces with commas
def replace_space_with_comma(my_string):
    return my_string.replace(" ",",")

# replacing spaces with commons in all chords in all rows of the data
chord_data.loc[:,'chords'] = chord_data['chords'].apply(replace_space_with_comma)
chord_data.sample(5)

chords  \
393620  G,C,C7,C,G,C,C7,C,G,D,C,G,C,C7,C,G,C,C7,C,G,D,...   
183065  <intro_1>,Dmin,Bb,F,C,Dmin,Bb,F,C,<verse_1>,Dm...   
504789  D7,A,D7,A,Fsmin,E,D,Dmin,D,A,Bmin,A,Fsmin,E,Dm...   
498000  G,Emin,G,D,D/Fs,B/Eb,Bmin,C,Emin,G,D,D/Fs,B/Eb...   
57250   <intro_1>,G,Emin,<verse_1>,G,Emin,C,Dsus4,D7,G...   

                                                   genres  
393620  baroque pop"chamber pop"indie rock"neo-psyched...  
183065   finnish dance pop"finnish pop"iskelma"suomi rock  
504789                          pinoy pop punk"pinoy rock  
498000  alternative metal"canadian pop punk"canadian p...  
57250                                                 NaN

In [7]:
# Remove section markers
def remove_section_markers(my_string):
    result = []
    i = 0
    n = len(my_string)
    while i < n:
        if my_string[i] == '<':
            # Skip until after the following ", "
            j = my_string.find('>', i)
            if j == -1:
                break  # no closing '>', stop
            i = j + 2  # skip '>,' and the space
        else:
            result.append(my_string[i])
            i += 1
    assert('<' not in result)
    assert('>' not in result)
    return ''.join(result)

chord_data.loc[:,'chords'] = chord_data['chords'].apply(remove_section_markers)
chord_data.sample(5)

chords  \
260422  G,Cadd9,G,Cadd9,G,Cadd9,G,Cadd9,G,Cadd9,G,Cadd...   
546790  G,C,G,D,G,C,G,C,G,D,G,C,G,D,G,C,G,D,G,C,G,D,G,...   
469064  Emin,D,Amin,Emin,D,Amin,Emin,D,Amin,Emin,D,Ami...   
306526  C7,F7,C7,G7,F7,G7,F7,C7,G7,C7,F7,C7,G7,F7,C7,G...   
640990  G,Emin,Amin,D,G,Emin,Amin,D,G,Emin,Amin,D,G,Em...   

                                                   genres  
260422  conscious hip hop"hip hop"north carolina hip h...  
546790                                        dutch indie  
469064                                                NaN  
306526                                                NaN  
640990                                                NaN

In [8]:
# Removing inversions
def remove_inversions(my_string):
    result = []
    i = 0
    n = len(my_string)
    while i < n:
        if my_string[i] == '/':
            # Skip until after the following ", "
            j = my_string.find(',', i)
            if j == -1:
                break  # no closing comma, stop
            i = j  # skip comma
        else:
            result.append(my_string[i])
            i += 1
    return ''.join(result)

In [9]:
# get some sample chords with inversions
songs_with_inversions = chord_data.loc[['/' in ch for ch in chord_data.chords]]
songs_with_inversions.sample(10)

# just a basic test on a random chord sequence with some inversions
n = 3
my_sample = songs_with_inversions.sample(n)
for i in range(n):
    s = my_sample.iloc[i].chords
    print(s)
    print()
    print(remove_inversions(s))
    print()
    print()

G,Bmin7,C7,G,Bmin7,Cadd9,G,Bmin7,Cadd9,G,Emin,Cadd9,G,Emin,Cadd9,G,Bmin7,Cadd9,G,Bmin7,Cadd9,G,Amin7,G/B,D,Emin,C,G,D/Fs,Emin,C,D,Emin,C,G,Bmin7,C,G,Emin,C,D,Emin,C,Emin,C,D,Emin,C,Emin,C,D,Emin,C,Emin,C,D,Emin,C,Emin,C,D,Emin,C,G

G,Bmin7,C7,G,Bmin7,Cadd9,G,Bmin7,Cadd9,G,Emin,Cadd9,G,Emin,Cadd9,G,Bmin7,Cadd9,G,Bmin7,Cadd9,G,Amin7,G,D,Emin,C,G,D,Emin,C,D,Emin,C,G,Bmin7,C,G,Emin,C,D,Emin,C,Emin,C,D,Emin,C,Emin,C,D,Emin,C,Emin,C,D,Emin,C,Emin,C,D,Emin,C,G


D,D/Cs,G,D,D/Cs,G,Emin,A,Emin,A,D,D/Cs,G,D,D/Cs,G,Emin,A,Emin,A,D,G,A,G,Bmin,A,G,D,A,Bmin,G,A,D,Emin,A,Emin,A,D,Emin,A,Emin,A,D,Emin,A,D

D,D,G,D,D,G,Emin,A,Emin,A,D,D,G,D,D,G,Emin,A,Emin,A,D,G,A,G,Bmin,A,G,D,A,Bmin,G,A,D,Emin,A,Emin,A,D,Emin,A,Emin,A,D,Emin,A,D


A,Csmin,A,A7,D,D/Cs,Bmin,E,A,Csmin,A,A7,D,D/Cs,Bmin,E,A,Csmin,A,A7,D,D/Cs,Bmin,E,A,Csmin,A,A7,D,D/Cs,Bmin,E,D,A,Fsmin,A,A7,D,A,Fsmin,A,E,A,Csmin,A,A7,D,D/Cs,Bmin,E,A,Csmin,A,A7,D,D/Cs,Bmin,E

A,Csmin,A,A7,D,D,Bmin,E,A,Csmin,A,A7,D,D,Bmin,E,A,Csmin,A,A7,D,D,Bmin,E,A,Csmin,A,A

In [10]:
# remove inversions from the whole data set
chord_data.loc[:,'chords'] = chord_data['chords'].apply(remove_inversions)
chord_data.sample(5)

chords  \
27010           A,E,D,A,E,D,A,E,D,A,E,D,A,E,D,A,E,D,A,E,D   
553138  Emin,D,C,D,C,D,C,D,Emin,D,C,D,C,D,C,D,G,D,G,D,...   
22885   C,G7,G,C,G7,G,C,G7,G,C,G7,G,C,G7,G,C,G7,G,C,G7...   
326605  Ab,Eb,Db,Ab,Eb,Db,Ab,Eb,Db,Ab,Db,Ab,Gb,Ab,Eb,D...   
26824   Bb,Dmin,Gmin,Cmin,Dmin,Bb,Dmin,Gmin,C,Dmin,F,G...   

                                                   genres  
27010                 classic texas country"texas country  
553138                                                NaN  
22885                                                 NaN  
326605  classical"italian opera"italian romanticism"la...  
26824                       family gospel"southern gospel

In [11]:
# compile a list of all chords in the data set
list_of_chord_lists = list(chord_data.chords)
giant_chord_string = ','.join(list_of_chord_lists)
data_set_chords = list(set(giant_chord_string.split(','))) # converting to a set as an intermediate step will get rid of duplicates
assert(len(data_set_chords) == len(set(data_set_chords))) # validating no duplicates

In [12]:
data_set_chords.remove('') # I still don't understand why the empty string ends up in here after what I'm doing above, but it does, so this gets rid of it. This is a very hacky solution.

In [13]:
print(list_of_chord_lists[0:5])
print()
print(giant_chord_string[0:200])
print()
print(len(data_set_chords))
print(data_set_chords[0:20])

['C,F,C,E7,Amin,C,F,C,G7,C,F,C,E7,Amin,C,F,G7,C,F,C,E7,Amin,C,F,C,G7,C,F,C,E7,Amin,C,F,G7,C,F,C,F,C,G,C,F,C,E7,Amin,C,F,G7,C,D,G,D,G,D,A,D,G,D,Fs7,Bmin,D,G,A7,D,G,A7,D', 'E,D,A,E,D,A,E,D,A,E,D,A,E,D,A,E,D,A,C,E,G,D,A,E,G,D,A,E,G,D,A,C,D,E,D,A,E,D,A,E,D,A,E,D,A,E,D,A,C,E,G,D,A,E,G,D,A,E,G,D,A,C,D,E,C,G,D,E,C,G,D,E,C,G,D,C,D,E,G,E,G,D,A,E,G,D,A,E,G,D,A,C,D,E,G,D,A,E,G,D,A,E,G,D,A,C,D,E,C,G,D,E,C,G,D,E,C,G,D,C,D,E', 'D,Dmaj7,D,Dmaj7,Emin,A,D,G,Emin,A,D,G,Emin,A,D,G,Emin,A,D,Emin,A,D,G,Emin,A,D,G,D,Emin,A,D,G,D,Emin,A,D,G,Emin,A,D,G,Emin,A,D,G,Emin,A,D,G,Emin,A,D,G,Emin,A,D,G,Emin,A,D,Emin,A,D,G,Emin,A,D,G,D,Emin,A,D,G,D,Emin,A,D,G,Emin,A,D,G,D,Emin,A,D,G,D,Emin,A,D,G,D,Emin,A,D,Emin,A,D,G,Emin,A,D,G,D,Emin,A,D,G,D,Emin,A,D,G,Emin,A,D,G,D,Emin,A,D,G,D,Emin,A,D,G,D,Emin,A,D,G,Emin,A,D,G,D', 'C,G,C,G,C,F,Dmin,G,Dmin,G,C,G,C,F,Dmin,G,Dmin,G,C,F,Dmin,G,Dmin7,G,C,G,C,F,Dmin,G,Dmin,G,C,F,Dmin,G,Dmin,G,C', 'C,G,C,G,C,G,C,G,C,Bmin,Emin,Amin,D,G,C,D,G,C,D,G,D,F,E,Amin,D,G,C,D,G,C,D,G,D,F,E,Amin,D,C

In [14]:
# list of all chords in the data set which are not in the chords_mapping csv file, should be basically zero
mystery_chords = list(set(data_set_chords).difference(set(known_chords)))
assert(len(mystery_chords) == len(set(mystery_chords))) # validating no duplicates
print(len(mystery_chords))
print(mystery_chords)

0
[]


In [15]:
# function to convert a string of comma-separated chords into a matrix, where each column denotes a chord
def string_to_chord_matrix(chord_sequence):
    # split sequence over commas, ignoring any "empty string" chords
    chord_list = [c for c in chord_sequence.split(',') if c != '']
    
    # then look up each chord in chord_degrees dictionary by the key value
    return np.array([chord_degrees[c][::-1] for c in chord_list]).transpose()

# visualizing the output for a sample of a few songs
n = 3
my_sample = chord_data.sample(n)
np.set_printoptions(linewidth=400)
for i in range(n):
    s = my_sample.iloc[i].chords
    print(s)
    print()
    print(string_to_chord_matrix(s))
    print()
    print()

D,D7,Bmin7,As7,D,D7,Bmin7,As7,D,D7,Bmin7,As7,D,D7,Bmin7,As7,D,D7,Bmin7,As7,D,D7,Bmin7,As7,D,D7,Bmin7,As7,D,D7,Bmin7,As7,D,D7,Bmin7,As7,D,D7,Bmin7,As7

[[0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0]
 [0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1]
 [1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0]
 [0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0]
 [0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0

In [16]:
# remove inversions from the whole data set
chord_data.insert(loc = 2,
                  column = 'chord_matrix',
                  value = chord_data['chords'].apply(string_to_chord_matrix),
                  allow_duplicates = False)
chord_data.sample(5)

chords  \
519780  A,B,Bb,D,G,D,A,G,A,D,A,G,A,D,A,G,A,D,A,G,A,D,A...   
270966  Cmin,As,Amin7,F,G,Cmin,As,Amin7,F,G,Cmin,As,Am...   
327468  Fmin,C,Cs,Ds,Fmin,C,Cs,Ds,Gs,C,Cs,Ds,Gs,C,Cs,D...   
468488  A,E,Fsmin,D,A,E,Fsmin,D,A,E,Fsmin,D,A,E,Fsmin,...   
312279  A,D,E,Csmin,G,F,Fs,Bb,Bmin,Gs,Eb,A,E,A,E,A,E,A...   

                                    genres  \
519780                                 emo   
270966             danish alternative rock   
327468               a cappella"vocal jazz   
468488  post-teen pop"talent show"teen pop   
312279                                 NaN   

                                             chord_matrix  
519780  [[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,...  
270966  [[0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,...  
327468  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...  
468488  [[0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,...  
312279  [[0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,...

In [17]:
# Illustration of how to transpose, in vector/matrix form
# For a vector chord, transposing is just a matter of cyclically permuting the vector
# It seems the easiest way to do this is using deque objects
# deque = "double-ended queue"
from collections import deque 

def transpose_chord_up(chord_vector, num_semitones):
    # transpose the input chord_vector up by num_semitones
    d = deque(chord_vector)
    d.rotate(num_semitones)
    return(list(d))

Cmaj_vec = chord_degrees['C']
Dmaj_vec = chord_degrees['D']
print("C major:\t\t",Cmaj_vec)
print("D major:\t\t",Dmaj_vec)
print("C major transposed up 2:",transpose_chord_up(Cmaj_vec,2))

C major:		 [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
D major:		 [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0]
C major transposed up 2: [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0]


In [18]:
def transpose_matrix_up(chord_matrix, num_semitones):
    # transpose the entire matrix up by a number of semitones
    # this just means applying transpose_chord_up to each column
    # we'll accomplish this by taking the matrix transpose, applying to each row, then taking the matrix transpose back
    transpose_matrix = np.transpose(np.copy(chord_matrix))
    for i in range(len(transpose_matrix)):
        transpose_matrix[i] = transpose_chord_up(transpose_matrix[i],-num_semitones) # the negative sign makes it musically transpose the correct direction, something about transposing the matrix
    return np.transpose(transpose_matrix)

# visualizing the output for a sample of a few songs
n = 1
my_sample = chord_data.sample(n)
np.set_printoptions(linewidth=400)
for i in range(n):
    s = my_sample.iloc[i].chords
    s_matrix = string_to_chord_matrix(s)

    semitones = 3
    shifted_matrix = transpose_matrix_up(s_matrix,semitones)
    
    print(s)
    print()
    print(s_matrix)
    print()
    print(shifted_matrix)
    print()
    print(transpose_matrix_up(s_matrix,semitones))
    print()

C,Amin,F,C,Amin,F,C,Amin,C,Amin,F,C,Amin,F,C,Amin,F,C,Amin,F,C,Amin,F,C,Amin,F,C,Amin,F,C,Amin,F,C,Amin,F,C,Amin,F,C

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0]
 [1 1 0 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [19]:
# make a version of the chord_degrees dictionary which is easier to look up by chord vector
# Note that it's not possible to make dictionary version of this where the key is a binary vector, because that isn't a hashable type
# Actually, I'm not sure this is useful, but I'll keep it here
reverse_chord_degrees = [tuple(x) for x in chord_degrees.items()]
reverse_chord_degrees[0:10]

[('C7', [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0]),
 ('Cmaj7', [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1]),
 ('C9', [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0]),
 ('Cmaj9', [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1]),
 ('Cmajs9', [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1]),
 ('Cb9', [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0]),
 ('Cb79', [1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0]),
 ('Cb7b9', [1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0]),
 ('C7b9', [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0]),
 ('C7sus2', [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0])]

In [20]:
# converting back from a chord matrix to a comma-separated string of chord names
# note that if you convert a string to a matrix and back, you can get enharmonic equivalents depending on the order things appear in the dictionary
# for example, F->vector->string can become Es (E sharp) when coming back to a string, because the chord_mapping.csv file lists both 
def chord_matrix_to_string(chord_matrix):
    # transpose the matrix so that rows are chord vectors
    transposed_matrix = np.transpose(chord_matrix)
    
    chord_string = ''

    # look up the row in chord mappings dictionary, add to our string
    for row in transposed_matrix:
        found = False
        for key, value in chord_degrees.items():
            if found==False and (row[::-1]==value).all(): # the found=False check avoids enharmonically equivalent chords being both added, e.g. Fs and Gb are the same as a vector
                chord_string = chord_string + key + ","
                found = True

    return chord_string[0:-1] # chop off the very last comma

# visualizing the output for a sample of a few songs
n = 1
my_sample = chord_data.sample(n)
np.set_printoptions(linewidth=400)
for i in range(n):
    s = my_sample.iloc[i].chords
    s_matrix = string_to_chord_matrix(s)
    s_again = chord_matrix_to_string(s_matrix)
    
    print(s)
    print()
    print(s_matrix)
    print()
    print(s_again)
    print()

D,A,Bmin,D,A,Bmin,D,A,Bmin,A,G,A,D,A,Bmin,D,A,Bmin,D,A,Bmin,A,G,A,G,A,G,A,G,A,G,A,D,A,Bmin,D,A,Bmin,D,A,Bmin,A,G,A,G,A,G,A,G,A,G,A,D,G,D,A,Bmin,D,A,A,G,A,G,A,G,A,G,A,D,G,D,G,D,G,D,A,Bmin

[[0 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 0 1 1 0 1 0 1 1 1 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0]
 [1 0 1 1 0 1 1 0 1 0 0 0 1

In [21]:
# comparing a transposed chord string with a shifted matrix to check for agreement
n = 1
my_sample = chord_data.sample(n)
np.set_printoptions(linewidth=600)
for i in range(n):
    s = my_sample.iloc[i].chords
    s_matrix = string_to_chord_matrix(s)

    semitones = 3
    shifted_matrix = transpose_matrix_up(s_matrix,semitones)
    shifted_string = chord_matrix_to_string(shifted_matrix)
    
    print(s)
    print()
    print(s_matrix)
    print()
    print(shifted_matrix)
    print()
    print(shifted_string)
    print()

G,D,Amin,G,C,Cmaj7,Cmin7,G,C,Cmaj7,Cmin7,D,G,D,G,Amin,Bmin,C,G,Amin,Bmin,C,G,D,Amin,G,C,Cmaj7,Cmin7,G,C,Cmaj7,Cmin7,D,G,D,G,Amin,Bmin,C,G,Amin,Bmin,C,G,Amin,Bmin,Amin,C,D,G,Amin,G,Amin,Bmin,C,G,Amin,Bmin,C

[[1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [22]:
note_names_sharps = ['C','Cs','D','Ds','E','F','Fs','G','Gs','A','As','B']
note_names_flats = ['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B']

In [23]:
# some possible features

def total_chords(chord_string):
    # count the number of total chords in a comma-separated string
    return len(chord_string.split(','))

def unique_chords(chord_string):
    # count the number of unique chords in a comma-separated string
    return len(set(chord_string.split(',')))

def unique_chord_ratio(chord_string):
    return float(unique_chords(chord_string)) / float(total_chords(chord_string))

def missing_notes(chord_string):
    # returns the number of notes missing, i.e. number of zero rows in the chord matrix
    chord_matrix = string_to_chord_matrix(chord_string)
    count = 0
    for row in chord_matrix:
        if not row.any():
            count += 1
    return count

def note_frequency(chord_string, relative=False):
    # return a vector of note counts
    # or if relative=True, return a percentage version of this, using the number of total chords as the denominator
    chord_matrix = string_to_chord_matrix(chord_string)
    count_vector = [np.sum(chord_matrix[i]) for i in range(12)]
    if relative == True:
        count_vector = list(np.array(count_vector) / total_chords(chord_string))
    return count_vector[::-1] # need to reverse to get "bottom-up"

def most_common_notes(chord_string, names = True, spelling = 'sharp'):
    frequency_vector = note_frequency(chord_string)
    max_frequency = np.max(frequency_vector)
    notes = []
    for i in range(12):
        if frequency_vector[i] == max_frequency:
            if names == True and spelling == 'sharp':
                notes.append(note_names_sharps[i])
            elif names == True and spelling == 'flat':
                notes.append(note_names_flats[i])
            else:
                notes.append(i)
    return notes


In [24]:
# more possible features

def drone_ratio(chord_string):
    # a metric of how close the song is to having a drone pitch
    # return the fraction of all chords that contain the most frequently appearing note
    # i.e. returns 1 if the most frequent single note appears in every chord, 0.5 if the most frequent note appears in half the chords
    return np.max(note_frequency(chord_string,relative=True))

def sequential_overlap(chord_string):
    # a measure of how much sequential pairs of chords overlap in notes
    chord_matrix = string_to_chord_matrix(chord_string)
    transposed_matrix = np.transpose(np.copy(chord_matrix))
    similarity_vector = np.zeros(shape = len(transposed_matrix) - 1, 
                                 dtype=int)
    for i in range(len(transposed_matrix) - 1):
        # look the ith row (chord), and compare with the following chord
        # take the dot product, which counts the number of overlapping notes
        similarity_vector[i] = np.dot(transposed_matrix[i],transposed_matrix[i+1])
    return list(similarity_vector)

def average_sequential_overlap(chord_string):
    return np.mean(sequential_overlap(chord_string))

def is_major_triad(chord_vector):
    # return true if chord_vector is a major triad
    C_triad = chord_degrees['C']
    for i in range(12):
        if np.array_equal(chord_vector[::-1], 
                          transpose_chord_up(C_triad,i)):
            return 1
    return 0

def major_triads(chord_string):
    # return a binary vector indicating where simple major triads occur
    return [is_major_triad(c) for c in np.transpose(string_to_chord_matrix(chord_string))]

def major_triad_ratio(chord_string):
    return np.mean(major_triads(chord_string))

In [25]:
def transpose_to_most_frequent_note(chord_string, chord_matrix):
    # take an input chord string, convert to a matrix, and transpose it to the most frequently appearing note
    # in case of ties, just throw an error
    
    # find the most common note
    common_notes = most_common_notes(chord_string, names = False)
    if len(common_notes) > 1:
        return('Unable to transpose to most frequent note, tied for most common notes')
    assert(len(common_notes) == 1)
    most_common_note = common_notes[0]

    # Transpose so that the most common note is now C
    # In other words, shift down by a number of semitones equal to the scale degree of the most common note
    shifted_chord_matrix = transpose_matrix_up(chord_matrix, -most_common_note)

    return shifted_chord_matrix

In [54]:
# basic visual tests of these metrics
my_sample = chord_data.sample(1)
np.set_printoptions(linewidth=600)
s = my_sample.iloc[0].chords
s_matrix = string_to_chord_matrix(s)
print(s)
print()
print(s_matrix)
print()
print("Total chords:",total_chords(s))
print("Unique chords:",unique_chords(s))
print("Unique chord ratio:",unique_chord_ratio(s))
print("Missing notes:",missing_notes(s))
print("Absolute note frequencies:",note_frequency(s,relative=False))
print("Relative note frequencies:",note_frequency(s,relative=True))
print("Most common notes:",most_common_notes(s, names = True, spelling = 'sharp'))
print("Drone ratio:",drone_ratio(s))
print("Sequential overlap:",sequential_overlap(s))
print("Average sequential overlap:",average_sequential_overlap(s))
print("Major triads:",major_triads(s))
print("Major triad ratio:",major_triad_ratio(s))
print()
print("Chord matrix transposed to C:")
print(transpose_to_most_frequent_note(s, s_matrix))

D,A,C,A,D,A,C,A,D,G,D,G,D,G,D,A,G,D,G,D,G,Fsmin,Bmin,Emin,A,G,D,A,G,D,G,D,G,Fsmin,Bmin,Emin,A,G,D,G,D,G,D,A,G,D,G,D,G,D,A,G,A,G,D,G,D,G,Fsmin,Bmin,Emin,A,D

[[0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 0 1 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [56]:
enumerate([1,2,3])

In [90]:
def get_subsequences(my_list, subsequence_length):
    # return all subsequences of a given length from a list
    assert(subsequence_length < len(my_list))
    return [my_list[i:i+subsequence_length] for i in range(len(my_list) - subsequence_length + 1)]

get_subsequences(my_list = [1,2,3,4,5,6,7,8,9,10], 
                 subsequence_length = 4)

[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10]]

In [92]:
def n_grams(chord_string, n):
    # compile a list of n-grams in the chord_string
    chord_matrix = string_to_chord_matrix(chord_string)
    transposed_matrix = np.transpose(np.copy(chord_matrix)) # now chord vectors are rows
    return get_subsequences(my_list = transposed_matrix,
                            subsequence_length = n)

In [94]:
# basic visual tests of these metrics
my_sample = chord_data.sample(1)
np.set_printoptions(linewidth=600)
s = my_sample.iloc[0].chords
s_matrix = string_to_chord_matrix(s)
print(s)
print()
print(s_matrix)
print()
print("2-grams:",n_grams(s,2))

Amin,G,F,C,D,C,F,G,Amin,Dmin,F,G,Amin,Emin,Cmaj7

[[0 1 0 0 0 0 0 1 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0 1 1 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1 0 0 0 1 0 1 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 1 1 0 0 0 0]
 [1 0 0 1 0 1 0 0 1 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 1 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 1 1 0 1 0 1 0 1 0 1]]

2-grams: [array([[0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]]), array([[1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1]]), array([[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1]]), array([[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0]]), array([[0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1]]), array([[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0,